[project]
name = "rclaptimes"
version = "0.1.0"
description = "Save and display RC laptimes"
authors = [
    {name = "datagutten",email = "datagutten@datagutten.net"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.1.1,<7.0.0)",
    "psycopg2-binary (>=2.9.13,<3.0.0)",
    "gunicorn (>=26.2.0,<27.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
openstint = [
    "pyzmq (>=27.2.0,<28.0.0)"
]
mylaps = [
    "ambp3parser @ git+https://github.com/datagutten/amb-p3-parser.git"
]
