# Generated by Django 6.1.1 on 2026-09-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='Decoder IP or hostname')),
                ('port', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('decoder_type', models.CharField(choices=[('mylaps', 'MyLaps'), ('openstint', 'OpenStint')])),
                ('enabled', models.BooleanField(default=True)),
                ('min_lap_time', models.IntegerField(blank=True, help_text='Minimum lap time (seconds)', null=True)),
                ('max_lap_time', models.IntegerField(blank=True, help_text='Maximum lap time (seconds)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('name', models.CharField(blank=True, null=True)),
                ('transponder_type', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(help_text='Milliseconds since 1970-01-01')),
                ('signal', models.IntegerField()),
                ('hit_count', models.IntegerField()),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.BinaryField(blank=True, null=True)),
                ('decoder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passings', to='laptimes.decoder')),
                ('transponder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passings', to='laptimes.transponder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time_ms', models.IntegerField()),
                ('lap_time', models.DurationField()),
                ('decoder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='laptimes.decoder')),
                ('passing1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lap', to='laptimes.passing')),
                ('passing2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lap2', to='laptimes.passing')),
                ('transponder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='laptimes.transponder')),
            ],
            options={
                'get_latest_by': ['passing1__time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('laps', models.ManyToManyField(to='laptimes.lap')),
                ('transponder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='laptimes.transponder')),
            ],
        ),
    ]
