# Generated by Django 6.1.1 on 2026-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoder',
            name='max_lap_time',
            field=models.IntegerField(default=30, help_text='Maximum lap time (seconds)'),
        ),
        migrations.AlterField(
            model_name='decoder',
            name='min_lap_time',
            field=models.IntegerField(default=10, help_text='Minimum lap time (seconds)'),
        ),
    ]
