# Generated by Django 6.1.1 on 2026-09-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0002_alter_decoder_max_lap_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='session',
            name='decoder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='laptimes.decoder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
