# Generated by Django 6.1.1 on 2026-09-27 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0003_alter_session_options_remove_session_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passing',
            name='saved_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Passing time from server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passing',
            name='time',
            field=models.DateTimeField(blank=True, help_text='Passing time from decoder', null=True),
        ),
    ]
