name: Publish OpenStint docker image
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  getversion:
    runs-on: ubuntu-latest
    name: Obtain OpenStint Version
    outputs:
      build-version: ${{ steps.set-version.outputs.openstint_version }}
    steps:
    - name: Set OpenStint Build Version
      id: set-version
      run: |
        if [[ ${GITHUB_REF} == refs/heads/* || ${GITHUB_REF} == refs/pull/* ]]; then
          # Build from latest OpenStint commit
          openstint_version=$(wget \
            -qO - https://api.github.com/repos/zsellera/openstint/releases/latest \
            | awk '/tag_name/{print $4;exit}' FS='[""]')
        else
          # Build tag
          openstint_version=${GITHUB_REF##*/}
        fi
        echo Building OpenStint ${openstint_version}
        echo "openstint_version=${openstint_version}" >> $GITHUB_OUTPUT

  build:
    name: Build and push release Docker Image
    runs-on: ubuntu-latest
    if: ${{ needs.getversion.outputs.build-version != '' }}
    needs: getversion
    env:
      OPENSTINT_VERSION: ${{ needs.getversion.outputs.build-version }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v7

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: openstint
        push: true
        build-args: |
          OPENSTINT_VERSION=${{env.OPENSTINT_VERSION}}
        tags: |
          ghcr.io/datagutten/openstint:${{ needs.getversion.outputs.build-version }}
          ghcr.io/datagutten/openstint:latest

  build_dev:
    name: Build and push development Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v7

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push development Docker image
      uses: docker/build-push-action@v7
      with:
        context: openstint
        push: true
        build-args: |
          OPENSTINT_VERSION=master
        tags: |
          ghcr.io/datagutten/openstint:development